#!/usr/bin/env python3
"""
LaTeX Table Generator for Clustering Results

Generates publication-ready LaTeX tables from clustering analysis results.

Usage:
    python generate_latex_tables.py \
        --summary results/clustering_summary.csv \
        --tests results/statistical_tests.csv \
        --output-dir tables/
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd


def load_data(summary_path: str, tests_path: Optional[str] = None):
    """Load summary and statistical tests data."""
    summary_df = pd.read_csv(summary_path)
    print(f"✓ Loaded summary: {len(summary_df)} rows")
    
    tests_df = None
    if tests_path and Path(tests_path).exists():
        tests_df = pd.read_csv(tests_path)
        print(f"✓ Loaded statistical tests: {len(tests_df)} rows")
    
    return summary_df, tests_df


def format_mean_std(mean: float, std: float, decimals: int = 4) -> str:
    """Format mean ± std for LaTeX."""
    if pd.isna(mean) or pd.isna(std):
        return "N/A"
    return f"${mean:.{decimals}f} \\pm {std:.{decimals}f}$"


def get_best_value_marker(
    value: float,
    all_values: List[float],
    higher_is_better: bool = True
) -> str:
    """Mark the best value in bold."""
    if pd.isna(value):
        return ''
    
    valid_values = [v for v in all_values if not pd.isna(v)]
    if not valid_values:
        return ''
    
    if higher_is_better:
        if abs(value - max(valid_values)) < 1e-6:
            return '\\textbf{'
    else:
        if abs(value - min(valid_values)) < 1e-6:
            return '\\textbf{'
    
    return ''


def generate_main_table(
    summary_df: pd.DataFrame,
    tests_df: pd.DataFrame,
    method: str,
    output_path: str
):
    """Generate main clustering results table for a specific method."""
    method_df = summary_df[summary_df['clustering_method'] == method]
    
    if len(method_df) == 0:
        print(f"⚠️  No data for method: {method}")
        return
    
    lines = []
    lines.append("% Clustering Results Table")
    lines.append(f"% Method: {method}")
    lines.append("% Generated by generate_latex_tables.py")
    lines.append("")
    lines.append("\\begin{table}[htbp]")
    lines.append("\\centering")
    lines.append("\\caption{Clustering Performance Comparison using " + 
                f"{method.replace('_', ' ').title()} (K=6)}")
    lines.append("\\label{tab:clustering_" + method + "}")
    lines.append("\\resizebox{\\textwidth}{!}{%")
    lines.append("\\begin{tabular}{lcccccc}")
    lines.append("\\toprule")
    lines.append("\\multirow{2}{*}{\\textbf{Model}} & " +
                "\\multicolumn{2}{c}{\\textbf{Silhouette Score}} & " +
                "\\multicolumn{2}{c}{\\textbf{Davies-Bouldin}} & " +
                "\\multicolumn{2}{c}{\\textbf{Calinski-Harabasz}} \\\\")
    lines.append("\\cmidrule(lr){2-3} \\cmidrule(lr){4-5} \\cmidrule(lr){6-7}")
    lines.append("& Mean & Std & Mean & Std & Mean & Std \\\\")
    lines.append("\\midrule")
    
    # Get all values for finding best
    sil_values = method_df['silhouette_mean'].tolist()
    db_values = method_df['davies_bouldin_mean'].tolist()
    ch_values = method_df['calinski_harabasz_mean'].tolist()
    
    for _, row in method_df.iterrows():
        model = row['model'].replace('_', '\\_')
        
        # Silhouette
        sil_mean = row.get('silhouette_mean', np.nan)
        sil_std = row.get('silhouette_std', np.nan)
        sil_best = get_best_value_marker(sil_mean, sil_values, higher_is_better=True)
        sil_str = format_mean_std(sil_mean, sil_std, 4)
        if sil_best:
            sil_str = sil_best + sil_str + "}"
        
        # Davies-Bouldin
        db_mean = row.get('davies_bouldin_mean', np.nan)
        db_std = row.get('davies_bouldin_std', np.nan)
        db_best = get_best_value_marker(db_mean, db_values, higher_is_better=False)
        db_str = format_mean_std(db_mean, db_std, 4)
        if db_best:
            db_str = db_best + db_str + "}"
        
        # Calinski-Harabasz
        ch_mean = row.get('calinski_harabasz_mean', np.nan)
        ch_std = row.get('calinski_harabasz_std', np.nan)
        ch_best = get_best_value_marker(ch_mean, ch_values, higher_is_better=True)
        ch_str = format_mean_std(ch_mean, ch_std, 2)
        if ch_best:
            ch_str = ch_best + ch_str + "}"
        
        lines.append(f"{model} & {sil_str} & {db_str} & {ch_str} \\\\")
    
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}%")
    lines.append("\\end{table}")
    
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write("\n".join(lines))
    
    print(f"✓ Saved main table: {output_path}")


def generate_statistical_tests_table(
    tests_df: pd.DataFrame,
    method: str,
    output_path: str
):
    """Generate statistical significance tests table."""
    if tests_df is None or len(tests_df) == 0:
        print("⚠️  No statistical tests data available")
        return
    
    method_tests = tests_df[tests_df['clustering_method'] == method]
    
    if len(method_tests) == 0:
        print(f"⚠️  No tests for method: {method}")
        return
    
    lines = []
    lines.append("% Statistical Significance Tests Table")
    lines.append(f"% Method: {method}")
    lines.append("% Generated by generate_latex_tables.py")
    lines.append("")
    lines.append("\\begin{table}[htbp]")
    lines.append("\\centering")
    lines.append("\\caption{Statistical Significance Tests vs Baseline (" +
                f"{method.replace('_', ' ').title()})}")
    lines.append("\\label{tab:statistical_tests_" + method + "}")
    lines.append("\\resizebox{\\textwidth}{!}{%")
    lines.append("\\begin{tabular}{lcccccc}")
    lines.append("\\toprule")
    lines.append("\\multirow{2}{*}{\\textbf{Metric}} & " +
                "\\multicolumn{2}{c}{\\textbf{T-Test}} & " +
                "\\multicolumn{2}{c}{\\textbf{Wilcoxon}} & " +
                "\\multirow{2}{*}{\\textbf{Effect Size}} \\\\")
    lines.append("\\cmidrule(lr){2-3} \\cmidrule(lr){4-5}")
    lines.append("& Statistic & $p$-value & Statistic & $p$-value & (Cohen's $d$) \\\\")
    lines.append("\\midrule")
    
    metrics = ['silhouette', 'davies_bouldin', 'calinski_harabasz']
    
    for metric in metrics:
        metric_tests = method_tests[method_tests['metric'] == metric]
        
        if len(metric_tests) == 0:
            continue
        
        # Get first test (should be same for all models if comparing to baseline)
        test_row = metric_tests.iloc[0]
        
        metric_display = metric.replace('_', ' ').title()
        
        # T-test
        t_stat = test_row.get('ttest_statistic', np.nan)
        t_pval = test_row.get('ttest_pvalue', np.nan)
        t_str = f"${t_stat:.4f}$" if not pd.isna(t_stat) else "N/A"
        t_pval_str = f"${t_pval:.4f}$" if not pd.isna(t_pval) else "N/A"
        
        # Wilcoxon
        w_stat = test_row.get('wilcoxon_statistic', np.nan)
        w_pval = test_row.get('wilcoxon_pvalue', np.nan)
        w_str = f"${w_stat:.4f}$" if not pd.isna(w_stat) else "N/A"
        w_pval_str = f"${w_pval:.4f}$" if not pd.isna(w_pval) else "N/A"
        
        # Effect size
        eff_size = test_row.get('cohens_d', np.nan)
        eff_str = f"${eff_size:.4f}$" if not pd.isna(eff_size) else "N/A"
        
        lines.append(f"{metric_display} & {t_str} & {t_pval_str} & " +
                    f"{w_str} & {w_pval_str} & {eff_str} \\\\")
    
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}%")
    lines.append("\\end{table}")
    
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write("\n".join(lines))
    
    print(f"✓ Saved statistical tests table: {output_path}")


def generate_summary_table_all_methods(
    summary_df: pd.DataFrame,
    output_path: str
):
    """Generate summary table showing all clustering methods."""
    lines = []
    lines.append("% Summary Table - All Clustering Methods")
    lines.append("% Generated by generate_latex_tables.py")
    lines.append("")
    lines.append("\\begin{table}[htbp]")
    lines.append("\\centering")
    lines.append("\\caption{Clustering Performance Summary Across Methods}")
    lines.append("\\label{tab:clustering_summary_all}")
    lines.append("\\resizebox{\\textwidth}{!}{%")
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\toprule")
    lines.append("\\textbf{Model} & \\textbf{Silhouette} & \\textbf{Davies-Bouldin} & " +
                "\\textbf{Calinski-Harabasz} & \\textbf{N Seeds} \\\\")
    lines.append("\\midrule")
    
    # Use first method as representative
    method = summary_df['clustering_method'].iloc[0]
    method_df = summary_df[summary_df['clustering_method'] == method]
    
    for _, row in method_df.iterrows():
        model = row['model'].replace('_', '\\_')
        sil = format_mean_std(row.get('silhouette_mean'), row.get('silhouette_std'), 4)
        db = format_mean_std(row.get('davies_bouldin_mean'), row.get('davies_bouldin_std'), 4)
        ch = format_mean_std(row.get('calinski_harabasz_mean'), row.get('calinski_harabasz_std'), 2)
        n_seeds = row['n_seeds']
        
        lines.append(f"{model} & {sil} & {db} & {ch} & {n_seeds} \\\\")
    
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}%")
    lines.append("\\end{table}")
    
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write("\n".join(lines))
    
    print(f"✓ Saved summary table: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate LaTeX tables from clustering analysis results',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate all tables
  python generate_latex_tables.py \\
      --summary results/clustering_summary.csv \\
      --tests results/statistical_tests.csv \\
      --output-dir tables/
  
  # Custom paths
  python generate_latex_tables.py \\
      --summary results/clustering_summary.csv \\
      --tests results/statistical_tests.csv \\
      --output-dir tables/clustering/
        """
    )
    
    parser.add_argument('--summary', type=str, required=True,
                        help='Summary CSV file')
    parser.add_argument('--tests', type=str, default=None,
                        help='Statistical tests CSV file (optional)')
    parser.add_argument('--output-dir', type=str, default='tables/',
                        help='Output directory for LaTeX tables')
    
    args = parser.parse_args()
    
    print("\n" + "="*80)
    print("📝 GENERATING LATEX TABLES")
    print("="*80)
    
    # Load data
    summary_df, tests_df = load_data(args.summary, args.tests)
    
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate tables for each clustering method
    for method in summary_df['clustering_method'].unique():
        print(f"\n📊 Generating tables for: {method}")
        
        # Main results table
        main_table_path = output_dir / f'table_clustering_{method}.tex'
        generate_main_table(summary_df, tests_df, method, str(main_table_path))
        
        # Statistical tests table
        if tests_df is not None:
            tests_table_path = output_dir / f'table_statistical_tests_{method}.tex'
            generate_statistical_tests_table(tests_df, method, str(tests_table_path))
    
    # Summary table (all methods)
    summary_table_path = output_dir / 'table_clustering_summary.tex'
    generate_summary_table_all_methods(summary_df, str(summary_table_path))
    
    print("\n" + "="*80)
    print("✅ LATEX TABLE GENERATION COMPLETE")
    print("="*80)
    print(f"Output directory: {output_dir}")
    print("="*80)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
